language: csharp
solution: Sibusten.Philomena.Api.sln
mono: none
dotnet: 5.0.101
os: linux
dist: xenial

# Define reusable jobs

test-job: &test-job
  stage: "Test"
  script: dotnet test -c $CONFIGURATION

deploy-job: &deploy-job
  stage: "Deploy"
  if: branch = main AND tag IS present
  script: dotnet pack ./Sibusten.Philomena.Api/Sibusten.Philomena.Api.csproj -c $CONFIGURATION
  deploy:
    provider: script
    edge: true
    script: dotnet nuget push ./Sibusten.Philomena.Api/bin/$CONFIGURATION/Sibusten.Philomena.Api.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

# Specify jobs to run

jobs:
  include:
    - <<: *test-job
      env: CONFIGURATION=Debug
    - <<: *test-job
      env: CONFIGURATION=Release

    - <<: *deploy-job
      env: CONFIGURATION=Release  # Only deploy with release configuration
